name: Deploy to Azure Web App

     on:
       push:
         branches: [ main ]

     jobs:
       build-and-deploy:
         runs-on: ubuntu-latest

         steps:
         # Checkout the repository
         - name: Checkout GitHub Action
           uses: actions/checkout@v4

         # Set up Python
         - name: Set up Python
           uses: actions/setup-python@v5
           with:
             python-version: '3.11'

         # Install dependencies
         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt

         # Deploy to Azure Web App
         - name: Deploy to Azure Web App
           uses: azure/webapps-deploy@v3
           with:
             app-name: house-price-app
             publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
             package: .